import * as Dialog from '@radix-ui/react-dialog';import {format} from 'date-fns';import {useEffect,useRef,useState,useSyncExternalStore} from 'react';import {apiRequest,ApiProblem} from './api.js';import type {Config} from './config.js';import {diagnostics} from './diagnostics.js';import {verifyLaunchDescriptor} from './descriptor.js';import {getErrorCopy} from './errors.js';import {acceptPlayerMessage} from './messages.js';import {installTabCloseClear,tokenStore,adminTokenStore} from './security.js';import {AdminWorkspace,adminSignIn} from './admin.js';
import {allowsDevelopmentSignIn,environmentNotice,OidcClient,session as providerSession} from '@lorb/web-auth';
/**
 * The notice a non-production portal carries, so a learner or a teacher can tell that the work they
 * are doing here is not the work of record. Production shows nothing.
 */
export const environmentNoticeFor=environmentNotice;
type ObjectRecord={object_id:string;repository_id:string;title?:string;status:string;active_package_version_id:string;active_object_version_id:string;description?:string;duration?:string;kind?:string};type Package={semver:string;sha256:string;delivery_profile:string};type Page='signin'|'catalogue'|'detail'|'launch'|'summary'|'error'|'admin';
const developmentIdentities=['learner-a','learner-b'];
export function App({config}: {config:Config}){const [page,setPage]=useState<Page>(tokenStore.get()?'catalogue':'signin');const [objects,setObjects]=useState<ObjectRecord[]>([]);const [selected,setSelected]=useState<ObjectRecord>();const [pkg,setPkg]=useState<Package>();const [launch,setLaunch]=useState<{player_url:string;signed_descriptor:string;correlation_id:string}>();const [notice,setNotice]=useState('');const [summary,setSummary]=useState<{complete:boolean;at:string;correlation:string;unsaved?:boolean}>();const [problem,setProblem]=useState<{code:string;correlation:string;recoverable:boolean}>();const [sessionEnd,setSessionEnd]=useState('');const [leak,setLeak]=useState(false);const frame=useRef<HTMLIFrameElement>(null);
 useEffect(()=>installTabCloseClear(),[]);useEffect(()=>{if(location.hash.startsWith('#/launch')&&!launch){setPage(tokenStore.get()?'catalogue':'signin');setNotice('Launch links cannot be reopened. Choose the activity from the catalogue.')}},[]);
 const load=async()=>{try{const repos=await apiRequest<{items:{repository_id:string}[]}>(config,'repositories',{},()=>setLeak(true));if(repos.items[0]){const data=await apiRequest<{items:ObjectRecord[]}>(config,`learning-objects?repository_id=${encodeURIComponent(repos.items[0].repository_id)}`,{},()=>setLeak(true));setObjects(data.items)}}catch(e){showProblem(e)}};
 useEffect(()=>{if(page==='catalogue')void load()},[page]);
 function showProblem(error:unknown,recoverable=false){const e=error instanceof ApiProblem?error:new ApiProblem('UNKNOWN_ERROR',crypto.randomUUID());setProblem({code:e.code,correlation:e.correlationId,recoverable});setPage('error')}
 // Sign-in. A configured identity provider is the only way in wherever one exists; the development
 // path below is unreachable in any other environment, and configuration refuses to build a portal
 // without a provider outside development.
 const oidc=useRef<OidcClient|undefined>(config.oidc?new OidcClient(config.oidc):undefined);
 useEffect(()=>{const client=oidc.current;if(!client)return;void client.completeSignIn().then(completed=>{const token=providerSession.token;if(completed&&token){tokenStore.set(token);setPage('catalogue')}}).catch(e=>showProblem(e,true))},[]);
 const signIn=async(index:number)=>{
  const client=oidc.current;
  if(client){await client.signIn().catch(e=>showProblem(e,true));return}
  if(!allowsDevelopmentSignIn(config.environment)){showProblem(new Error('No identity provider is configured for this environment.'),false);return}
  try{const response=await fetch(config.developmentLoginUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({subject:developmentIdentities[index]})});if(!response.ok)throw new Error('Sign-in failed');const body=await response.json() as {access_token:string};tokenStore.set(body.access_token);setPage('catalogue')}catch(e){showProblem(e,true)}
 };
 const signOut=()=>{tokenStore.clear();setObjects([]);setPage('signin');oidc.current?.signOut(location.origin)};
 const adminOut=()=>{adminTokenStore.clear();setPage('signin')};
 const enterAdmin=async()=>{try{await adminSignIn(config,'teacher-a');setPage('admin')}catch(e){showProblem(e,true)}};
 const detail=async(object:ObjectRecord)=>{setSelected(object);try{const data=await apiRequest<Package>(config,`package-versions/${object.active_package_version_id}`,{},()=>setLeak(true));setPkg(data);setPage('detail')}catch(e){showProblem(e)}};
 const launchObject=async()=>{if(!selected)return;try{const data=await apiRequest<{player_url:string;signed_descriptor:string;correlation_id:string}>(config,'launches',{method:'POST',body:JSON.stringify({contract_version:'1.0',consumer_id:'learner-portal',repository_id:selected.repository_id,object_id:selected.object_id,requested_launch_mode:'embedded-iframe',locale:'en-GB'})});await verifyLaunchDescriptor(data.signed_descriptor,config);if(new URL(data.player_url).origin!==config.playerShellOrigin)throw new Error('Player URL origin mismatch');setLaunch(data);setPage('launch');location.hash='/launch'}catch(e){showProblem(e,true)}};
 useEffect(()=>{if(page!=='launch')return;const handler=(event:MessageEvent)=>{const message=acceptPlayerMessage(event,config.allowedShellOrigins,frame.current?.contentWindow??null);if(!message)return;const p=message.payload as any;if(message.type==='module.resize'&&Number(p.width)<=1200&&Number(p.height)<=900&&Number(p.width)>0&&Number(p.height)>0&&frame.current){frame.current.width=String(p.width);frame.current.height=String(p.height)}else if(message.type==='session.expiring'){setSessionEnd(String(p.expires_at))}else if(message.type==='experience.complete'){setSummary({complete:true,at:new Date().toISOString(),correlation:message.correlation_id});setPage('summary');location.hash=''}else if(message.type==='experience.exit'){if(p.safe_to_close===false&&p.unsaved_state===true&&!confirm('Your progress may not have been saved. Close this activity?'))return;setSummary({complete:false,at:new Date().toISOString(),correlation:message.correlation_id,unsaved:Boolean(p.unsaved_state)});setPage('summary');location.hash=''}else if(message.type==='experience.error'){setProblem({code:String(p.code),correlation:message.correlation_id,recoverable:Boolean(p.recoverable)});setPage('error')}};window.addEventListener('message',handler);return()=>window.removeEventListener('message',handler)},[page,config]);
 const back=()=>{setLaunch(undefined);setProblem(undefined);setSummary(undefined);setNotice('');setPage('catalogue');location.hash=''};
 const notice_=environmentNoticeFor(config.environment);const banner=notice_?<div className="environment-notice" role="note">{notice_}</div>:null;if(page==='launch')return <><a className="skip" href="#main">Skip to content</a>{banner}<main id="main" className="launch"><div className="launch-strip"><strong>{selected?.title??'Learning activity'}</strong><button onClick={()=>setPage('catalogue')}>Close activity</button></div>{sessionEnd&&<div className="session">Your session will end at {format(new Date(sessionEnd),'HH:mm')}. Save your work if needed.</div>}<div className="sr-only" aria-live="polite">{sessionEnd&&`Your session will end at ${format(new Date(sessionEnd),'HH:mm')}. Save your work if needed.`}</div>{launch&&<iframe ref={frame} title={selected?.title??'Learning activity'} src={launch.player_url} sandbox="allow-scripts" width="1200" height="900"/>}</main></>;
 return <><a className="skip" href="#main">Skip to content</a><Header environment={config.environment} signedIn={page!=='signin'} signOut={signOut}/>{banner}{leak&&<div role="alert">SUSPECTED_LEAK — response data was withheld.</div>}<div className="small-screen">The learner portal is designed for tablet or desktop. Please widen your window or use a larger screen.</div><main id="main">{notice&&<p className="notice">{notice}</p>}{page==='signin'&&(config.oidc
  ?<section><h1>Sign in</h1><p>You will be taken to your organisation&rsquo;s sign-in page.</p><button onClick={()=>void signIn(0)}>Continue to sign in</button></section>
  :<section><h1>Sign in</h1><p>No identity provider is configured for this development environment, so a local learner is used.</p>{developmentIdentities.map((x,i)=><button key={x} onClick={()=>void signIn(i)}>Continue as {x}</button>)}<hr/><p>Teachers manage classes, learners and assignments in the administration area.</p><button onClick={()=>void enterAdmin()}>Continue as a teacher</button></section>)}{page==='admin'&&<AdminWorkspace config={config} onSignOut={adminOut} onSignInAgain={()=>adminSignIn(config,'teacher-a')}/>}{page==='catalogue'&&<section><h1>Catalogue</h1><div className="grid">{objects.map(o=><button className="card" key={o.object_id} onClick={()=>void detail(o)}><strong>{o.title??'Untitled learning activity'}</strong><span>{o.kind??'native-web-package'}</span><span>Duration: {o.duration??'not stated'}</span><span>Active version: {o.active_object_version_id}</span></button>)}</div></section>}{page==='detail'&&selected&&<section><button className="back" onClick={back}>← Catalogue</button><h1>{selected.title??'Untitled learning activity'}</h1><p>{selected.description??'No description is available.'}</p><dl><dt>Delivery profile</dt><dd>{pkg?.delivery_profile}</dd><dt>Active version</dt><dd>{pkg?.semver}</dd><dt>Package SHA-256</dt><dd>{pkg?.sha256.slice(0,12)}</dd></dl><button onClick={()=>void launchObject()}>Launch activity</button></section>}{page==='summary'&&summary&&<section><h1>{summary.complete?'Activity complete':'Activity closed'}</h1>{summary.complete&&<p>Completed at {format(new Date(summary.at),'d MMMM yyyy, HH:mm')}</p>}{summary.unsaved&&<p>Your progress may not have been saved. Try again from the catalogue.</p>}<p>Correlation ID: {summary.correlation}</p><button onClick={back}>Return to catalogue</button></section>}{page==='error'&&problem&&<ErrorCard problem={problem} retry={()=>void launchObject()} back={back} signIn={()=>{tokenStore.clear();setPage('signin')}}/>}</main><Diagnostics/></>}
function Header({environment,signedIn,signOut}:{environment:string;signedIn:boolean;signOut:()=>void}){return <header><span className="wordmark">LORB Learner Portal</span>{environment!=='PRODUCTION'&&<span className="environment">{environment}</span>}{signedIn&&<button onClick={signOut}>Sign out</button>}</header>}
function ErrorCard({problem,retry,back,signIn}:{problem:{code:string;correlation:string;recoverable:boolean};retry:()=>void;back:()=>void;signIn:()=>void}){const copy=getErrorCopy(problem.code,problem.correlation);return <section className="error"><h1>{copy.title}</h1><p>{copy.detail}</p>{problem.recoverable&&<button onClick={retry}>Retry</button>}{copy.actions.includes('Sign in' as never)?<button onClick={signIn}>Sign in</button>:<button onClick={back}>Return to catalogue</button>}<details><summary>Diagnostics</summary><p>Correlation ID: {problem.correlation}</p></details></section>}
function Diagnostics(){const events=useSyncExternalStore(diagnostics.subscribe,diagnostics.snapshot,diagnostics.snapshot);const [open,setOpen]=useState(false);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.ctrlKey&&e.altKey&&e.key.toLowerCase()==='d')setOpen(true)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger className="diagnostics">Diagnostics</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="drawer"><Dialog.Title>Diagnostics</Dialog.Title><Dialog.Description>In-memory integration events. Sensitive values are redacted.</Dialog.Description><ul>{events.map((e,i)=><li key={`${e.at}-${i}`}>{e.at} — {e.kind} — {e.correlationId} {e.errorCode}</li>)}</ul><Dialog.Close>Close</Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>}
