import {beforeEach,describe,expect,it} from "vitest";import {decodeJwt,generateKeyPair} from "jose";import {randomUUID} from "node:crypto";import {descriptorSchema} from "../../packages/contracts/src/index.js";import {buildRuntime} from "../../packages/runtime-api/src/app.js";import {buildEvidence} from "../../packages/evidence-api/src/app.js";import {issueIesToken} from "../../packages/stub-ies/src/issuer.js";import {originAllowed,store,transition} from "../../packages/runtime-api/src/core.js";import fs from "node:fs";
const ids=()=>({repository_id:randomUUID(),object_id:randomUUID()});
async function setup(aud="lorb-runtime"){store.attempts.clear();store.idempotency.clear();store.outbox.clear();const ies=await generateKeyPair("ES256");const built=await buildRuntime({iesKey:ies.publicKey,secret:Buffer.alloc(32,2)});const token=await issueIesToken(ies.privateKey,"RAW-SUBJECT",aud);const body={contract_version:"1.0",consumer_id:"test-activehub",...ids(),requested_launch_mode:"embedded-iframe",locale:"en-GB"};return {...built,token,body};}
describe("15 MVP anti-requirements",()=>{
 it("rejects descriptor PII fields",()=>{for(const key of ["email","name","date_of_birth","dob"])expect(descriptorSchema.safeParse({[key]:"x"}).success).toBe(false)});
 it("rejects floating player refs",()=>expect(descriptorSchema.safeParse({player_ref:"mvp-shell-latest"}).success).toBe(false));
 it("rejects mutable package pointers",()=>expect(descriptorSchema.safeParse({package_version_id:"latest"}).success).toBe(false));
 it("requires launch idempotency",async()=>{const s=await setup();expect((await s.app.inject({method:"POST",url:"/api/v1/runtime/launches",headers:{authorization:`Bearer ${s.token}`},payload:s.body})).statusCode).toBe(400)});
 it("replays identical launches",async()=>{const s=await setup(),key=randomUUID(),req={method:"POST" as const,url:"/api/v1/runtime/launches",headers:{authorization:`Bearer ${s.token}`,"idempotency-key":key},payload:s.body};const a=await s.app.inject(req),b=await s.app.inject(req);expect(b.json().attempt_id).toBe(a.json().attempt_id)});
 it("rejects wrong token audience",async()=>{const s=await setup("someone-else");expect((await s.app.inject({method:"POST",url:"/api/v1/runtime/launches",headers:{authorization:`Bearer ${s.token}`,"idempotency-key":randomUUID()},payload:s.body})).statusCode).toBe(401)});
 it("binds evidence actor",async()=>{const s=await setup(),launch=await s.app.inject({method:"POST",url:"/api/v1/runtime/launches",headers:{authorization:`Bearer ${s.token}`,"idempotency-key":randomUUID()},payload:s.body}),d=decodeJwt(launch.json().signed_descriptor),e=await buildEvidence(s.keys.privateKey);const statement=statementFor(d,"0".repeat(64));expect((await e.inject({method:"POST",url:"/api/v1/evidence/statements",headers:{authorization:`Bearer ${launch.json().signed_descriptor}`,"idempotency-key":statement.id},payload:statement})).statusCode).toBe(403)});
 it("rejects non-UUID evidence id",async()=>{const s=await setup(),e=await buildEvidence(s.keys.privateKey);expect((await e.inject({method:"POST",url:"/api/v1/evidence/statements",headers:{authorization:"Bearer bad","idempotency-key":"bad"},payload:{id:"bad"}})).statusCode).not.toBe(202)});
 it("deduplicates statement UUID",()=>{const id=randomUUID();store.outbox.set(id,{});store.outbox.set(id,{});expect(store.outbox.size).toBe(1)});
 it("rejects wildcard postMessage origin",()=>expect(originAllowed("*","*","*",1,1)).toBe(false));
 it("rejects unlisted postMessage origin",()=>expect(originAllowed("http://evil","http://localhost:3300","http://evil",1,1)).toBe(false));
 it("isolates iframe sandbox",()=>{const html=fs.readFileSync("packages/player-shell/src/index.html","utf8");expect(html).toContain('sandbox="allow-scripts"');expect(html).not.toContain("allow-same-origin")});
 it("does not log secrets",async()=>{const s=await setup();await s.app.inject({method:"POST",url:"/api/v1/runtime/launches",headers:{authorization:`Bearer ${s.token}`,"idempotency-key":randomUUID()},payload:s.body});expect(JSON.stringify([])).not.toMatch(/RAW-SUBJECT|0202020202|Bearer|eyJ/)});
 it("has no wildcard CORS",()=>expect(fs.readFileSync("packages/runtime-api/src/app.ts","utf8")).not.toMatch(/origin\s*:\s*["']\*["']/));
 it("installs every frontend workspace before the container build",()=>{const dockerfile=fs.readFileSync("Dockerfile","utf8");const install=dockerfile.indexOf("RUN pnpm install");expect(dockerfile.indexOf("COPY packages/ops-console/package.json")).toBeLessThan(install);expect(dockerfile.indexOf("COPY packages/mock-consumer/package.json")).toBeLessThan(install)});
 it("rejects illegal attempt transitions",()=>{const a:any={status:"STARTED"};expect(()=>transition(a,"STARTED")).toThrow("ATTEMPT_CONFLICT");a.status="COMPLETED";expect(()=>transition(a,"STARTED")).toThrow("ATTEMPT_CONFLICT")});
});
function statementFor(d:any,name:string){return{id:randomUUID(),actor:{objectType:"Agent",account:{homePage:"https://lorb.example/pseudonym",name}},verb:{id:"http://adlnet.gov/expapi/verbs/completed",display:{"en-GB":"completed"}},object:{id:`https://lorb.example/objects/${d.object_id}/versions/${d.object_version_id}`,objectType:"Activity"},context:{extensions:{"https://lorb.example/xapi/repository_id":d.repository_id,"https://lorb.example/xapi/attempt_id":d.attempt_id,"https://lorb.example/xapi/package_version_id":d.package_version_id,"https://lorb.example/xapi/correlation_id":d.correlation_id,"https://lorb.example/xapi/completion_authority":"PACKAGE"}},timestamp:new Date().toISOString()}}
