import {createRemoteJWKSet,jwtVerify} from "jose";
import {postMessageSchema} from "../../contracts/src/index.js";
import {originAllowed} from "./postmessage.js";

type Descriptor={iss:string;aud:string;attempt_id:string;correlation_id:string;state_endpoint:string;evidence_endpoint:string;package_url:string;sub:string;object_id:string;object_version_id:string;repository_id:string;package_version_id:string;session_config:{expires_at:string}};
const frame=document.querySelector<HTMLIFrameElement>("#module")!;
const status=document.querySelector<HTMLElement>("#status")!;
const parentOrigin=document.referrer?new URL(document.referrer).origin:"";
const emit=(type:string,payload:Record<string,unknown>)=>parent.postMessage({protocol:"lorb-player",version:"1.0",type,message_id:crypto.randomUUID(),correlation_id:descriptor?.correlation_id??crypto.randomUUID(),reply_to:null,sent_at:new Date().toISOString(),payload},parentOrigin||location.origin);
let descriptor:Descriptor|undefined;
let revision=1;
async function request(url:string,method:string,body?:unknown){const response=await fetch(url,{method,headers:{authorization:`Bearer ${token()}`,'content-type':'application/json','idempotency-key':crypto.randomUUID()},body:body===undefined?undefined:JSON.stringify(body)});if(!response.ok)throw new Error(`Runtime request failed (${response.status})`);return response.json()}
function token(){return decodeURIComponent(location.hash.match(/(?:^#|&)descriptor=([^&]+)/)?.[1]??"")}
async function start(){try{const signed=token();if(!signed)throw new Error("Launch descriptor is missing");const unverified=JSON.parse(atob(signed.split('.')[1]!.replace(/-/g,'+').replace(/_/g,'/'))) as Descriptor;const jwks=createRemoteJWKSet(new URL(`${unverified.iss.replace(/\/$/,'')}/api/v1/runtime/jwks`));descriptor=(await jwtVerify(signed,jwks,{issuer:unverified.iss,audience:"lorb-player",algorithms:["ES256"]})).payload as unknown as Descriptor;frame.src=descriptor.package_url;status.textContent="Learning activity loaded"}catch(error){status.textContent="This activity could not be opened.";emit("experience.error",{code:"LAUNCH_INVALID",recoverable:false,detail:error instanceof Error?error.message:"Unknown error"})}}
window.addEventListener("message",async event=>{if(!descriptor||!originAllowed(event.origin,new URL(descriptor.package_url).origin,new URL(frame.src).origin,event.source,frame.contentWindow))return;const parsed=postMessageSchema.safeParse(event.data);if(!parsed.success)return;const message=parsed.data;try{if(message.type==="state.put"){const result=await request(descriptor.state_endpoint,"PUT",{revision,state_payload:message.payload.state??{}}) as {revision:number};revision=result.revision}else if(message.type==="evidence.emit"){await request(descriptor.evidence_endpoint,"POST",message.payload.statement)}else if(message.type==="experience.complete"){await request(descriptor.state_endpoint.replace(/\/state$/,"/complete"),"POST");emit("experience.complete",{})}else if(message.type==="experience.exit"){emit("experience.exit",message.payload)}else if(message.type==="experience.error"){emit("experience.error",message.payload)}}catch(error){emit("experience.error",{code:"PLAYER_ROUTE_FAILED",recoverable:true,detail:error instanceof Error?error.message:"Unknown error"})}});
void start();
