import Fastify from "fastify";
import cors from "@fastify/cors";
import helmet from "@fastify/helmet";
import { randomUUID } from "node:crypto";
import { jwtVerify, type KeyLike } from "jose";
import { launchRequestSchema } from "../../contracts/src/index.js";
import { computePseudonym } from "./services/pseudonym-service.js";
import { issueDescriptor, signingKeys, store, transition, verifyDescriptor } from "./core.js";

const problem=(code:string,status:number,correlation_id:string)=>({type:`https://lorb.example/errors/${code}`,title:code==="AUTHENTICATION_EXPIRED"?"Your session has expired":"We could not complete that request",status,code,detail:code==="AUTHENTICATION_EXPIRED"?"Sign in again to continue":"Please check the request and try again",correlation_id,retryable:status>=500,field_errors:[]});
export async function buildRuntime(options?:{iesKey?:KeyLike;secret?:Buffer}){
 const app=Fastify({logger:false,bodyLimit:65536}); const keys=await signingKeys(); const iesKey=options?.iesKey??keys.privateKey; const secret=options?.secret??Buffer.alloc(32,1);
 await app.register(helmet); await app.register(cors,{origin:(origin,cb)=>cb(null,!origin||(process.env.ALLOWED_CONSUMER_ORIGINS??"http://localhost:3300").split(",").includes(origin))});
 app.get("/api/v1/runtime/jwks",async()=>({keys:[keys.publicJwk]}));
 app.post("/api/v1/runtime/launches",async(req,reply)=>{const correlation=typeof req.headers["x-correlation-id"]==="string"?req.headers["x-correlation-id"]:randomUUID();const idem=req.headers["idempotency-key"];if(typeof idem!=="string")return reply.code(400).type("application/problem+json").send(problem("LAUNCH_CONTEXT_INVALID",400,correlation));if(store.idempotency.has(idem))return reply.code(201).send(store.idempotency.get(idem));let body;try{body=launchRequestSchema.parse(req.body);}catch{return reply.code(400).type("application/problem+json").send(problem("LAUNCH_CONTEXT_INVALID",400,correlation));}let claims;try{const token=req.headers.authorization?.replace(/^Bearer /,"");if(!token)throw 0;claims=(await jwtVerify(token,iesKey,{issuer:"http://localhost:4000",audience:"lorb-runtime",algorithms:["ES256"]})).payload;if(!claims.sub)throw 0;}catch{return reply.code(401).type("application/problem+json").send(problem("AUTHENTICATION_EXPIRED",401,correlation));}const attempt_id=randomUUID(),launch_id=randomUUID(),object_version_id=randomUUID(),package_version_id=randomUUID();const pseudonym=computePseudonym(secret,"http://localhost:4000",claims.sub as string,"launch");store.attempts.set(attempt_id,{attempt_id,repository_id:body.repository_id,object_version_id,package_version_id,pseudonym,status:"CREATED",revision:1});const expires=new Date(Date.now()+600000).toISOString();const descriptor=await issueDescriptor(keys.privateKey,{sub:pseudonym,repository_id:body.repository_id,consumer_id:body.consumer_id,object_id:body.object_id,object_version_id,package_version_id,correlation_id:correlation,locale:body.locale,attempt_id,state_endpoint:`http://localhost:3000/api/v1/runtime/attempts/${attempt_id}/state`,session_config:{expires_at:expires}});const response={launch_id,attempt_id,signed_descriptor:descriptor,player_url:`http://localhost:3200/?launch=${launch_id}`,expires_at:expires,correlation_id:correlation};store.launches.set(launch_id,response);store.idempotency.set(idem,response);return reply.code(201).send(response)});
 async function auth(req:any,reply:any){try{const token=req.headers.authorization?.replace(/^Bearer /,"");if(!token)throw 0;return await verifyDescriptor(token,keys.privateKey as KeyLike);}catch{reply.code(401).type("application/problem+json").send(problem("SESSION_EXPIRED",401,randomUUID()));}}
 app.put("/api/v1/runtime/attempts/:attemptId/state",async(req:any,reply)=>{if(!req.headers["idempotency-key"])return reply.code(400).send(problem("LAUNCH_CONTEXT_INVALID",400,randomUUID()));const d=await auth(req,reply);if(!d)return;const attempt=store.attempts.get(req.params.attemptId);const body=req.body as any;if(!attempt||d.attempt_id!==attempt.attempt_id||body?.revision!==attempt.revision)return reply.code(409).send(problem("ATTEMPT_CONFLICT",409,d.correlation_id));if(JSON.stringify(body.state_payload).length>65536||/(email|name|dob|date_of_birth|address)/i.test(JSON.stringify(Object.keys(body.state_payload??{}))))return reply.code(400).send(problem("LAUNCH_CONTEXT_INVALID",400,d.correlation_id));attempt.state=body.state_payload;attempt.revision++;if(attempt.status==="CREATED")transition(attempt,"STARTED");return reply.send({revision:attempt.revision,correlation_id:d.correlation_id});});
 app.post("/api/v1/runtime/attempts/:attemptId/complete",async(req:any,reply)=>{if(!req.headers["idempotency-key"])return reply.code(400).send(problem("LAUNCH_CONTEXT_INVALID",400,randomUUID()));const d=await auth(req,reply);if(!d)return;const attempt=store.attempts.get(req.params.attemptId);try{if(!attempt)throw 0;transition(attempt,"COMPLETED");return reply.send({attempt_id:attempt.attempt_id,status:attempt.status,correlation_id:d.correlation_id});}catch{return reply.code(409).send(problem("ATTEMPT_CONFLICT",409,d.correlation_id));}});
 return {app,keys};
}
