import Fastify, { type FastifyInstance } from "fastify"; import { randomUUID } from "node:crypto"; import { type KeyLike } from "jose"; import { xapiStatementSchema } from "../../contracts/src/index.js"; import { store,verifyDescriptor } from "../../runtime-api/src/core.js"; import { aggregateActivityResults } from "./read-model.js";
/** Registers the Evidence API routes onto any Fastify instance. The MVP store is process-local
 * in-memory state shared with the Runtime API (see core.ts), so in a deployed PoC these routes must
 * be mounted in the Runtime API's process — see src/server.ts. */
export function registerEvidenceRoutes(app:FastifyInstance,key:KeyLike,issuer:string=(process.env.RUNTIME_PUBLIC_ISSUER??"http://localhost:3000").replace(/\/$/,"")){app.post("/api/v1/evidence/statements",async(req,reply)=>{const idem=req.headers["idempotency-key"];if(typeof idem!=="string")return reply.code(400).send({code:"LAUNCH_CONTEXT_INVALID"});let d;try{d=await verifyDescriptor(req.headers.authorization?.replace(/^Bearer /,"")??"",key,issuer);}catch{return reply.code(401).send({code:"SESSION_EXPIRED"});}let statement;try{statement=xapiStatementSchema.parse(req.body);}catch{return reply.code(400).send({code:"LAUNCH_CONTEXT_INVALID"});}if(statement.actor.account.name!==d.sub)return reply.code(403).send({code:"ACCESS_DENIED"});if(!store.outbox.has(statement.id))store.outbox.set(statement.id,{outbox_id:randomUUID(),statement_id:statement.id,payload:statement,status:"PENDING",attempts:0,created_at:new Date().toISOString()});return reply.code(202).send({statement_id:statement.id,status:"PENDING",correlation_id:d.correlation_id});});
 app.get("/api/v1/evidence/outbox",async(req:any)=>({items:[...store.outbox.values()].filter((row:any)=>!req.query.status||row.status===req.query.status),next_cursor:null,correlation_id:req.headers["x-correlation-id"]??randomUUID()}));
 app.get("/api/v1/evidence/outbox/:outboxId",async(req:any,reply)=>[...store.outbox.values()].find((row:any)=>row.outbox_id===req.params.outboxId)??reply.code(404).send({code:"OBJECT_NOT_FOUND"}));
 app.post("/api/v1/evidence/outbox/:outboxId/replay",async(req:any,reply)=>{if(typeof req.headers["idempotency-key"]!=="string")return reply.code(400).send({code:"LAUNCH_CONTEXT_INVALID"});const row:any=[...store.outbox.values()].find((candidate:any)=>candidate.outbox_id===req.params.outboxId);if(!row||row.status!=="FAILED")return reply.code(409).send({code:"ATTEMPT_CONFLICT"});if((req.body as any)?.statement_id!==row.statement_id)return reply.code(409).send({code:"ATTEMPT_CONFLICT"});row.status="PENDING";row.attempts=(row.attempts??0)+1;return reply.code(202).send({attempt_id:randomUUID(),statement_id:row.statement_id,correlation_id:req.headers["x-correlation-id"]??randomUUID()});});
 // Teacher-facing aggregation for one learning object. Returns pseudonyms only: resolving a pseudonym
 // back to a named learner is a display-layer concern for the caller that holds the roster mapping.
 app.get("/api/v1/evidence/activity-results",async(req:any,reply)=>{const correlation=typeof req.headers["x-correlation-id"]==="string"?req.headers["x-correlation-id"]:randomUUID();const objectId=req.query?.object_id;if(typeof objectId!=="string"||!/^[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}$/i.test(objectId))return reply.code(400).send({code:"LAUNCH_CONTEXT_INVALID",correlation_id:correlation});return {...aggregateActivityResults(objectId),correlation_id:correlation};});
}
export async function buildEvidence(key:KeyLike,issuer?:string){const app=Fastify({logger:false});registerEvidenceRoutes(app,key,issuer);return app;}
